import { ChalkColor, Language, Translation } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  [Language.ZH_CN]: {
    title: '极简黑板',
    boards: '黑板列表',
    addBoard: '新建黑板',
    clear: '清空',
    eraser: '黑板擦',
    proModalTitle: '解锁无限黑板',
    proModalDesc: '当前仅可使用 4 个免费黑板。请我喝杯咖啡解锁无限创作空间！',
    proAction: '去打赏',
    close: '关闭',
    aiAnalyze: 'AI 讲解',
    aiAnalyzing: '思考中...',
    aiPrompt: '帮我分析黑板上的内容，如果是数学题请解答，如果是画作请鉴赏，如果是文字请翻译或总结。使用中文回答。',
  },
  [Language.ZH_TW]: {
    title: '極簡黑板',
    boards: '黑板列表',
    addBoard: '新增黑板',
    clear: '清空',
    eraser: '板擦',
    proModalTitle: '解鎖無限黑板',
    proModalDesc: '當前僅可使用 4 個免費黑板。請我喝杯咖啡解鎖無限創作空間！',
    proAction: '去打賞',
    close: '關閉',
    aiAnalyze: 'AI 講解',
    aiAnalyzing: '思考中...',
    aiPrompt: '幫我分析黑板上的內容，如果是數學題請解答，如果是畫作請鑑賞，如果是文字請翻譯或總結。使用繁體中文回答。',
  },
  [Language.EN]: {
    title: 'Zen Board',
    boards: 'Boards',
    addBoard: 'New Board',
    clear: 'Clear',
    eraser: 'Eraser',
    proModalTitle: 'Unlock Limitless Boards',
    proModalDesc: 'You are limited to 4 free boards. Buy me a coffee to unlock unlimited space!',
    proAction: 'Donate',
    close: 'Close',
    aiAnalyze: 'AI Explain',
    aiAnalyzing: 'Thinking...',
    aiPrompt: 'Analyze the contents of this blackboard. If it is math, solve it. If art, critique it. If text, summarize it. Answer in English.',
  },
  [Language.JA]: {
    title: '禅・黒板',
    boards: '黒板リスト',
    addBoard: '新規作成',
    clear: '消去',
    eraser: '黒板消し',
    proModalTitle: '無制限モードを解除',
    proModalDesc: '無料版は4枚までです。コーヒーを奢って無制限モードを解除しましょう！',
    proAction: '寄付する',
    close: '閉じる',
    aiAnalyze: 'AI 解説',
    aiAnalyzing: '思考中...',
    aiPrompt: '黒板の内容を分析してください。数学なら解き方を、絵なら感想を、文字なら要約を日本語で教えてください。',
  },
};

export const CHALK_COLORS = [
  ChalkColor.WHITE,
  ChalkColor.RED,
  ChalkColor.YELLOW,
  ChalkColor.BLUE,
  ChalkColor.GREEN,
];